// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockMetaService creates a new instance of MockMetaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetaService {
	mock := &MockMetaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetaService is an autogenerated mock type for the MetaService type
type MockMetaService struct {
	mock.Mock
}

type MockMetaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetaService) EXPECT() *MockMetaService_Expecter {
	return &MockMetaService_Expecter{mock: &_m.Mock}
}

// AggregateStats provides a mock function for the type MockMetaService
func (_mock *MockMetaService) AggregateStats(ctx context.Context) (*AggregateStatsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AggregateStats")
	}

	var r0 *AggregateStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*AggregateStatsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *AggregateStatsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AggregateStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetaService_AggregateStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateStats'
type MockMetaService_AggregateStats_Call struct {
	*mock.Call
}

// AggregateStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetaService_Expecter) AggregateStats(ctx interface{}) *MockMetaService_AggregateStats_Call {
	return &MockMetaService_AggregateStats_Call{Call: _e.mock.On("AggregateStats", ctx)}
}

func (_c *MockMetaService_AggregateStats_Call) Run(run func(ctx context.Context)) *MockMetaService_AggregateStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetaService_AggregateStats_Call) Return(aggregateStatsResponse *AggregateStatsResponse, err error) *MockMetaService_AggregateStats_Call {
	_c.Call.Return(aggregateStatsResponse, err)
	return _c
}

func (_c *MockMetaService_AggregateStats_Call) RunAndReturn(run func(ctx context.Context) (*AggregateStatsResponse, error)) *MockMetaService_AggregateStats_Call {
	_c.Call.Return(run)
	return _c
}

// CIDStats provides a mock function for the type MockMetaService
func (_mock *MockMetaService) CIDStats(ctx context.Context, cidStr string) (*CIDStatsResponse, error) {
	ret := _mock.Called(ctx, cidStr)

	if len(ret) == 0 {
		panic("no return value specified for CIDStats")
	}

	var r0 *CIDStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*CIDStatsResponse, error)); ok {
		return returnFunc(ctx, cidStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *CIDStatsResponse); ok {
		r0 = returnFunc(ctx, cidStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CIDStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cidStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetaService_CIDStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CIDStats'
type MockMetaService_CIDStats_Call struct {
	*mock.Call
}

// CIDStats is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
func (_e *MockMetaService_Expecter) CIDStats(ctx interface{}, cidStr interface{}) *MockMetaService_CIDStats_Call {
	return &MockMetaService_CIDStats_Call{Call: _e.mock.On("CIDStats", ctx, cidStr)}
}

func (_c *MockMetaService_CIDStats_Call) Run(run func(ctx context.Context, cidStr string)) *MockMetaService_CIDStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetaService_CIDStats_Call) Return(cIDStatsResponse *CIDStatsResponse, err error) *MockMetaService_CIDStats_Call {
	_c.Call.Return(cIDStatsResponse, err)
	return _c
}

func (_c *MockMetaService_CIDStats_Call) RunAndReturn(run func(ctx context.Context, cidStr string) (*CIDStatsResponse, error)) *MockMetaService_CIDStats_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockMetaService
func (_mock *MockMetaService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockMetaService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockMetaService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockMetaService_Expecter) Config() *MockMetaService_Config_Call {
	return &MockMetaService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockMetaService_Config_Call) Run(run func()) *MockMetaService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetaService_Config_Call) Return(manager config.Manager) *MockMetaService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockMetaService_Config_Call) RunAndReturn(run func() config.Manager) *MockMetaService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockMetaService
func (_mock *MockMetaService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockMetaService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockMetaService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockMetaService_Expecter) Context() *MockMetaService_Context_Call {
	return &MockMetaService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockMetaService_Context_Call) Run(run func()) *MockMetaService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetaService_Context_Call) Return(context1 core.Context) *MockMetaService_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockMetaService_Context_Call) RunAndReturn(run func() core.Context) *MockMetaService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockMetaService
func (_mock *MockMetaService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockMetaService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockMetaService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockMetaService_Expecter) DB() *MockMetaService_DB_Call {
	return &MockMetaService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockMetaService_DB_Call) Run(run func()) *MockMetaService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetaService_DB_Call) Return(dB *gorm.DB) *MockMetaService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockMetaService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockMetaService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// ExportDAG provides a mock function for the type MockMetaService
func (_mock *MockMetaService) ExportDAG(ctx context.Context, rootCIDStr string) (*DAGExportResponse, error) {
	ret := _mock.Called(ctx, rootCIDStr)

	if len(ret) == 0 {
		panic("no return value specified for ExportDAG")
	}

	var r0 *DAGExportResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*DAGExportResponse, error)); ok {
		return returnFunc(ctx, rootCIDStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *DAGExportResponse); ok {
		r0 = returnFunc(ctx, rootCIDStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DAGExportResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rootCIDStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetaService_ExportDAG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportDAG'
type MockMetaService_ExportDAG_Call struct {
	*mock.Call
}

// ExportDAG is a helper method to define mock.On call
//   - ctx context.Context
//   - rootCIDStr string
func (_e *MockMetaService_Expecter) ExportDAG(ctx interface{}, rootCIDStr interface{}) *MockMetaService_ExportDAG_Call {
	return &MockMetaService_ExportDAG_Call{Call: _e.mock.On("ExportDAG", ctx, rootCIDStr)}
}

func (_c *MockMetaService_ExportDAG_Call) Run(run func(ctx context.Context, rootCIDStr string)) *MockMetaService_ExportDAG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetaService_ExportDAG_Call) Return(dAGExportResponse *DAGExportResponse, err error) *MockMetaService_ExportDAG_Call {
	_c.Call.Return(dAGExportResponse, err)
	return _c
}

func (_c *MockMetaService_ExportDAG_Call) RunAndReturn(run func(ctx context.Context, rootCIDStr string) (*DAGExportResponse, error)) *MockMetaService_ExportDAG_Call {
	_c.Call.Return(run)
	return _c
}

// ExportSiaObject provides a mock function for the type MockMetaService
func (_mock *MockMetaService) ExportSiaObject(ctx context.Context, cidStr string) (*CIDExportResponse, error) {
	ret := _mock.Called(ctx, cidStr)

	if len(ret) == 0 {
		panic("no return value specified for ExportSiaObject")
	}

	var r0 *CIDExportResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*CIDExportResponse, error)); ok {
		return returnFunc(ctx, cidStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *CIDExportResponse); ok {
		r0 = returnFunc(ctx, cidStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CIDExportResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cidStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetaService_ExportSiaObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportSiaObject'
type MockMetaService_ExportSiaObject_Call struct {
	*mock.Call
}

// ExportSiaObject is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
func (_e *MockMetaService_Expecter) ExportSiaObject(ctx interface{}, cidStr interface{}) *MockMetaService_ExportSiaObject_Call {
	return &MockMetaService_ExportSiaObject_Call{Call: _e.mock.On("ExportSiaObject", ctx, cidStr)}
}

func (_c *MockMetaService_ExportSiaObject_Call) Run(run func(ctx context.Context, cidStr string)) *MockMetaService_ExportSiaObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetaService_ExportSiaObject_Call) Return(cIDExportResponse *CIDExportResponse, err error) *MockMetaService_ExportSiaObject_Call {
	_c.Call.Return(cIDExportResponse, err)
	return _c
}

func (_c *MockMetaService_ExportSiaObject_Call) RunAndReturn(run func(ctx context.Context, cidStr string) (*CIDExportResponse, error)) *MockMetaService_ExportSiaObject_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockMetaService
func (_mock *MockMetaService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMetaService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockMetaService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockMetaService_Expecter) ID() *MockMetaService_ID_Call {
	return &MockMetaService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockMetaService_ID_Call) Run(run func()) *MockMetaService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetaService_ID_Call) Return(s string) *MockMetaService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMetaService_ID_Call) RunAndReturn(run func() string) *MockMetaService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockMetaService
func (_mock *MockMetaService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockMetaService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockMetaService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockMetaService_Expecter) Logger() *MockMetaService_Logger_Call {
	return &MockMetaService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockMetaService_Logger_Call) Run(run func()) *MockMetaService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetaService_Logger_Call) Return(logger *core.Logger) *MockMetaService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockMetaService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockMetaService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// ProtocolStats provides a mock function for the type MockMetaService
func (_mock *MockMetaService) ProtocolStats(ctx context.Context) (*ProtocolStatsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProtocolStats")
	}

	var r0 *ProtocolStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ProtocolStatsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ProtocolStatsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProtocolStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetaService_ProtocolStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProtocolStats'
type MockMetaService_ProtocolStats_Call struct {
	*mock.Call
}

// ProtocolStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetaService_Expecter) ProtocolStats(ctx interface{}) *MockMetaService_ProtocolStats_Call {
	return &MockMetaService_ProtocolStats_Call{Call: _e.mock.On("ProtocolStats", ctx)}
}

func (_c *MockMetaService_ProtocolStats_Call) Run(run func(ctx context.Context)) *MockMetaService_ProtocolStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetaService_ProtocolStats_Call) Return(protocolStatsResponse *ProtocolStatsResponse, err error) *MockMetaService_ProtocolStats_Call {
	_c.Call.Return(protocolStatsResponse, err)
	return _c
}

func (_c *MockMetaService_ProtocolStats_Call) RunAndReturn(run func(ctx context.Context) (*ProtocolStatsResponse, error)) *MockMetaService_ProtocolStats_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockMetaService
func (_mock *MockMetaService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockMetaService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockMetaService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockMetaService_Expecter) SetConfig(cfg interface{}) *MockMetaService_SetConfig_Call {
	return &MockMetaService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockMetaService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockMetaService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetaService_SetConfig_Call) Return() *MockMetaService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetaService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockMetaService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockMetaService
func (_mock *MockMetaService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockMetaService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockMetaService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockMetaService_Expecter) SetContext(ctx interface{}) *MockMetaService_SetContext_Call {
	return &MockMetaService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockMetaService_SetContext_Call) Run(run func(ctx core.Context)) *MockMetaService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetaService_SetContext_Call) Return() *MockMetaService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetaService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockMetaService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockMetaService
func (_mock *MockMetaService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockMetaService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockMetaService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockMetaService_Expecter) SetDB(db interface{}) *MockMetaService_SetDB_Call {
	return &MockMetaService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockMetaService_SetDB_Call) Run(run func(db *gorm.DB)) *MockMetaService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetaService_SetDB_Call) Return() *MockMetaService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetaService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockMetaService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockMetaService
func (_mock *MockMetaService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockMetaService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockMetaService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockMetaService_Expecter) SetLogger(logger interface{}) *MockMetaService_SetLogger_Call {
	return &MockMetaService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockMetaService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockMetaService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetaService_SetLogger_Call) Return() *MockMetaService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetaService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockMetaService_SetLogger_Call {
	_c.Run(run)
	return _c
}
